# ---

AT := @

verbose:
	$(eval AT :=)
	@echo > /dev/null
.PHONY: verbose

test:
	$(AT) echo test
.PHONY: test

# ---

SHELL := /usr/bin/env bash -euo pipefail -c

env:
	@echo $(SHELL)
.PHONY: env

# ---
